### ISSUE TITLE
merging with other themes ?

### ISSUE THREAD

**Issue by HazemDa1st** [Daksh777/SpotifyNoPremium#25]
I am using the dribblish v2 theme with specitify 2.7 and spotify 1.1.69 ,

can I use the code in your css file and add it to the dribblish css file ?

**Comment by Daksh777** [comment]
You surely can, just copy from lines 61-133 of `user.css` and paste it into the `user.css` of the other theme.
https://github.com/Daksh777/SpotifyNoPremium/blob/9a039f1ad318657a5e7c3227f6173c9f7a62a524/user.css#L61-L133

**Comment by HazemDa1st** [comment]
@Daksh777  
I tried to do so what it doesn't work however when I apply your them it works.
 any tip on where to paste  61-133 lines in the dribblish v2 css file ?

**Comment by Daksh777** [comment]
I've submitted a [PR](https://github.com/morpheusthewhite/spicetify-themes/pull/562) to hide those elements.
Meanwhile, you can add these lines in your `user.css` file and remove the ones copied from my theme:
```css
.main-topBar-UpgradeButton {
    display: none
}
.main-contextMenu-menuItemButton[href="https://www.spotify.com/premium/"] {
    display: none
}
.main-leaderboardComponent-container {
    display: none
}
```
